[project]
name = "fortias"
dynamic = ["version"]
description = "Free, Open-source and Resilient Time Integrity Attestation Service"
readme = "README.md"
license = { text = "BSD 3-Clause Clear License" }
requires-python = ">=3.10"

classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
dependencies = [
    "cryptography>=42",
]

[project.optional-dependencies]
dev = [
    "pytest>=8",
]

[project.urls]
Homepage = "https://github.com/frcusaca/fortias"
Repository = "https://github.com/frcusaca/fortias"


[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback = "0.0.1"

[tool.hatch.build.hooks.vcs]
version-file = "src/fortias/_version.py"
