/* automatically generated by rust-bindgen 0.70.1 */

pub const FORTIAS_CORE_VERSION_MAJOR: u32 = 0;
pub const FORTIAS_CORE_VERSION_MINOR: u32 = 1;
pub const FORTIAS_NOISE_MAX_MSG: u32 = 65535;
pub const FORTIAS_MERKLE_MAX_DEPTH: u32 = 32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasCoreVersion {
    pub major: ::std::os::raw::c_int,
    pub minor: ::std::os::raw::c_int,
    pub build_hash: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FortiasCoreVersion"][::std::mem::size_of::<FortiasCoreVersion>() - 16usize];
    ["Alignment of FortiasCoreVersion"][::std::mem::align_of::<FortiasCoreVersion>() - 8usize];
    ["Offset of field: FortiasCoreVersion::major"]
        [::std::mem::offset_of!(FortiasCoreVersion, major) - 0usize];
    ["Offset of field: FortiasCoreVersion::minor"]
        [::std::mem::offset_of!(FortiasCoreVersion, minor) - 4usize];
    ["Offset of field: FortiasCoreVersion::build_hash"]
        [::std::mem::offset_of!(FortiasCoreVersion, build_hash) - 8usize];
};
extern "C" {
    pub fn fortias_core_version() -> FortiasCoreVersion;
}
pub const FortiasResult_FORTIAS_OK: FortiasResult = 0;
pub const FortiasResult_FORTIAS_ERR_BAD_SIG: FortiasResult = -1;
pub const FortiasResult_FORTIAS_ERR_BAD_PROOF: FortiasResult = -2;
pub const FortiasResult_FORTIAS_ERR_BAD_KEY: FortiasResult = -3;
pub const FortiasResult_FORTIAS_ERR_STALE: FortiasResult = -4;
pub const FortiasResult_FORTIAS_ERR_REPLAY: FortiasResult = -5;
pub const FortiasResult_FORTIAS_ERR_BAD_INPUT: FortiasResult = -6;
pub const FortiasResult_FORTIAS_ERR_OVERFLOW: FortiasResult = -7;
pub const FortiasResult_FORTIAS_ERR_UNSUPPORTED: FortiasResult = -8;
pub const FortiasResult_FORTIAS_ERR_INTERNAL: FortiasResult = -99;
pub type FortiasResult = ::std::os::raw::c_int;
pub const FortiasCurve_FORTIAS_CURVE_ED25519: FortiasCurve = 1;
pub const FortiasCurve_FORTIAS_CURVE_P256: FortiasCurve = 2;
pub type FortiasCurve = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasPubKey32 {
    pub bytes: [u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FortiasPubKey32"][::std::mem::size_of::<FortiasPubKey32>() - 32usize];
    ["Alignment of FortiasPubKey32"][::std::mem::align_of::<FortiasPubKey32>() - 1usize];
    ["Offset of field: FortiasPubKey32::bytes"]
        [::std::mem::offset_of!(FortiasPubKey32, bytes) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasPubKey33 {
    pub bytes: [u8; 33usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FortiasPubKey33"][::std::mem::size_of::<FortiasPubKey33>() - 33usize];
    ["Alignment of FortiasPubKey33"][::std::mem::align_of::<FortiasPubKey33>() - 1usize];
    ["Offset of field: FortiasPubKey33::bytes"]
        [::std::mem::offset_of!(FortiasPubKey33, bytes) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasPrivKey32 {
    pub bytes: [u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FortiasPrivKey32"][::std::mem::size_of::<FortiasPrivKey32>() - 32usize];
    ["Alignment of FortiasPrivKey32"][::std::mem::align_of::<FortiasPrivKey32>() - 1usize];
    ["Offset of field: FortiasPrivKey32::bytes"]
        [::std::mem::offset_of!(FortiasPrivKey32, bytes) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasPeerID {
    pub bytes: [u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FortiasPeerID"][::std::mem::size_of::<FortiasPeerID>() - 32usize];
    ["Alignment of FortiasPeerID"][::std::mem::align_of::<FortiasPeerID>() - 1usize];
    ["Offset of field: FortiasPeerID::bytes"]
        [::std::mem::offset_of!(FortiasPeerID, bytes) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasSig64 {
    pub bytes: [u8; 64usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FortiasSig64"][::std::mem::size_of::<FortiasSig64>() - 64usize];
    ["Alignment of FortiasSig64"][::std::mem::align_of::<FortiasSig64>() - 1usize];
    ["Offset of field: FortiasSig64::bytes"][::std::mem::offset_of!(FortiasSig64, bytes) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasHash32 {
    pub bytes: [u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FortiasHash32"][::std::mem::size_of::<FortiasHash32>() - 32usize];
    ["Alignment of FortiasHash32"][::std::mem::align_of::<FortiasHash32>() - 1usize];
    ["Offset of field: FortiasHash32::bytes"]
        [::std::mem::offset_of!(FortiasHash32, bytes) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasHash16 {
    pub bytes: [u8; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FortiasHash16"][::std::mem::size_of::<FortiasHash16>() - 16usize];
    ["Alignment of FortiasHash16"][::std::mem::align_of::<FortiasHash16>() - 1usize];
    ["Offset of field: FortiasHash16::bytes"]
        [::std::mem::offset_of!(FortiasHash16, bytes) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasHash20 {
    pub bytes: [u8; 20usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FortiasHash20"][::std::mem::size_of::<FortiasHash20>() - 20usize];
    ["Alignment of FortiasHash20"][::std::mem::align_of::<FortiasHash20>() - 1usize];
    ["Offset of field: FortiasHash20::bytes"]
        [::std::mem::offset_of!(FortiasHash20, bytes) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasNullifier {
    pub bytes: [u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FortiasNullifier"][::std::mem::size_of::<FortiasNullifier>() - 32usize];
    ["Alignment of FortiasNullifier"][::std::mem::align_of::<FortiasNullifier>() - 1usize];
    ["Offset of field: FortiasNullifier::bytes"]
        [::std::mem::offset_of!(FortiasNullifier, bytes) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasFrostShare {
    pub bytes: [u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FortiasFrostShare"][::std::mem::size_of::<FortiasFrostShare>() - 32usize];
    ["Alignment of FortiasFrostShare"][::std::mem::align_of::<FortiasFrostShare>() - 1usize];
    ["Offset of field: FortiasFrostShare::bytes"]
        [::std::mem::offset_of!(FortiasFrostShare, bytes) - 0usize];
};
extern "C" {
    pub fn fortias_ed25519_generate_keypair(
        pub_out: *mut FortiasPubKey32,
        priv_out: *mut FortiasPrivKey32,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_ed25519_derive_peer_id(
        pub_: *const FortiasPubKey32,
        id_out: *mut FortiasPeerID,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_ed25519_sign(
        priv_: *const FortiasPrivKey32,
        msg: *const u8,
        msg_len: usize,
        sig_out: *mut FortiasSig64,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_ed25519_verify(
        pub_: *const FortiasPubKey32,
        msg: *const u8,
        msg_len: usize,
        sig: *const FortiasSig64,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_p256_generate_keypair(
        pub_out: *mut FortiasPubKey33,
        priv_out: *mut FortiasPrivKey32,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_p256_derive_peer_id(
        pub_: *const FortiasPubKey33,
        id_out: *mut FortiasPeerID,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_p256_sign(
        priv_: *const FortiasPrivKey32,
        msg: *const u8,
        msg_len: usize,
        sig_out: *mut FortiasSig64,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_p256_verify(
        pub_: *const FortiasPubKey33,
        msg: *const u8,
        msg_len: usize,
        sig: *const FortiasSig64,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_hash_sha256(
        data: *const u8,
        len: usize,
        out: *mut FortiasHash32,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_hash_sha256_concat(
        a: *const u8,
        a_len: usize,
        b: *const u8,
        b_len: usize,
        out: *mut FortiasHash32,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_hash_blake3(
        data: *const u8,
        len: usize,
        out: *mut FortiasHash32,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_hash_legacy_insecure_md5(
        data: *const u8,
        len: usize,
        out: *mut FortiasHash16,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_hash_legacy_insecure_sha1(
        data: *const u8,
        len: usize,
        out: *mut FortiasHash20,
    ) -> FortiasResult;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasNoiseState {
    pub chaining_key: [u8; 32usize],
    pub handshake_hash: [u8; 32usize],
    pub local_static_priv: [u8; 32usize],
    pub local_static_pub: [u8; 32usize],
    pub local_ephemeral: [u8; 32usize],
    pub remote_ephemeral: [u8; 32usize],
    pub remote_static: [u8; 32usize],
    pub send_key: [u8; 32usize],
    pub recv_key: [u8; 32usize],
    pub send_nonce: u64,
    pub recv_nonce: u64,
    pub step: i32,
    pub is_initiator: i32,
    pub handshake_complete: i32,
    pub curve: i32,
    pub _pad: [u8; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FortiasNoiseState"][::std::mem::size_of::<FortiasNoiseState>() - 328usize];
    ["Alignment of FortiasNoiseState"][::std::mem::align_of::<FortiasNoiseState>() - 8usize];
    ["Offset of field: FortiasNoiseState::chaining_key"]
        [::std::mem::offset_of!(FortiasNoiseState, chaining_key) - 0usize];
    ["Offset of field: FortiasNoiseState::handshake_hash"]
        [::std::mem::offset_of!(FortiasNoiseState, handshake_hash) - 32usize];
    ["Offset of field: FortiasNoiseState::local_static_priv"]
        [::std::mem::offset_of!(FortiasNoiseState, local_static_priv) - 64usize];
    ["Offset of field: FortiasNoiseState::local_static_pub"]
        [::std::mem::offset_of!(FortiasNoiseState, local_static_pub) - 96usize];
    ["Offset of field: FortiasNoiseState::local_ephemeral"]
        [::std::mem::offset_of!(FortiasNoiseState, local_ephemeral) - 128usize];
    ["Offset of field: FortiasNoiseState::remote_ephemeral"]
        [::std::mem::offset_of!(FortiasNoiseState, remote_ephemeral) - 160usize];
    ["Offset of field: FortiasNoiseState::remote_static"]
        [::std::mem::offset_of!(FortiasNoiseState, remote_static) - 192usize];
    ["Offset of field: FortiasNoiseState::send_key"]
        [::std::mem::offset_of!(FortiasNoiseState, send_key) - 224usize];
    ["Offset of field: FortiasNoiseState::recv_key"]
        [::std::mem::offset_of!(FortiasNoiseState, recv_key) - 256usize];
    ["Offset of field: FortiasNoiseState::send_nonce"]
        [::std::mem::offset_of!(FortiasNoiseState, send_nonce) - 288usize];
    ["Offset of field: FortiasNoiseState::recv_nonce"]
        [::std::mem::offset_of!(FortiasNoiseState, recv_nonce) - 296usize];
    ["Offset of field: FortiasNoiseState::step"]
        [::std::mem::offset_of!(FortiasNoiseState, step) - 304usize];
    ["Offset of field: FortiasNoiseState::is_initiator"]
        [::std::mem::offset_of!(FortiasNoiseState, is_initiator) - 308usize];
    ["Offset of field: FortiasNoiseState::handshake_complete"]
        [::std::mem::offset_of!(FortiasNoiseState, handshake_complete) - 312usize];
    ["Offset of field: FortiasNoiseState::curve"]
        [::std::mem::offset_of!(FortiasNoiseState, curve) - 316usize];
    ["Offset of field: FortiasNoiseState::_pad"]
        [::std::mem::offset_of!(FortiasNoiseState, _pad) - 320usize];
};
extern "C" {
    pub fn fortias_noise_init_ed25519(
        state: *mut FortiasNoiseState,
        my_static_priv: *const FortiasPrivKey32,
        their_static_pub: *const FortiasPubKey32,
        is_initiator: bool,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_noise_init_p256(
        state: *mut FortiasNoiseState,
        my_static_priv: *const FortiasPrivKey32,
        their_static_pub: *const FortiasPubKey33,
        is_initiator: bool,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_noise_step(
        state: *mut FortiasNoiseState,
        input: *const u8,
        input_len: usize,
        output: *mut u8,
        output_len: *mut usize,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_noise_send(
        state: *mut FortiasNoiseState,
        plaintext: *const u8,
        pt_len: usize,
        ciphertext: *mut u8,
        ct_len: *mut usize,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_noise_recv(
        state: *mut FortiasNoiseState,
        ciphertext: *const u8,
        ct_len: usize,
        plaintext: *mut u8,
        pt_len: *mut usize,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_noise_destroy(state: *mut FortiasNoiseState);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasMerkleProof {
    pub siblings: [FortiasHash32; 32usize],
    pub directions: [u8; 32usize],
    pub depth: i32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FortiasMerkleProof"][::std::mem::size_of::<FortiasMerkleProof>() - 1060usize];
    ["Alignment of FortiasMerkleProof"][::std::mem::align_of::<FortiasMerkleProof>() - 4usize];
    ["Offset of field: FortiasMerkleProof::siblings"]
        [::std::mem::offset_of!(FortiasMerkleProof, siblings) - 0usize];
    ["Offset of field: FortiasMerkleProof::directions"]
        [::std::mem::offset_of!(FortiasMerkleProof, directions) - 1024usize];
    ["Offset of field: FortiasMerkleProof::depth"]
        [::std::mem::offset_of!(FortiasMerkleProof, depth) - 1056usize];
};
extern "C" {
    pub fn fortias_merkle_leaf(
        data: *const u8,
        len: usize,
        leaf_out: *mut FortiasHash32,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_merkle_verify(
        root: *const FortiasHash32,
        leaf: *const FortiasHash32,
        proof: *const FortiasMerkleProof,
    ) -> FortiasResult;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasFrostRound1 {
    pub nonce_d: [u8; 32usize],
    pub nonce_e: [u8; 32usize],
    pub commit_D: [u8; 32usize],
    pub commit_E: [u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FortiasFrostRound1"][::std::mem::size_of::<FortiasFrostRound1>() - 128usize];
    ["Alignment of FortiasFrostRound1"][::std::mem::align_of::<FortiasFrostRound1>() - 1usize];
    ["Offset of field: FortiasFrostRound1::nonce_d"]
        [::std::mem::offset_of!(FortiasFrostRound1, nonce_d) - 0usize];
    ["Offset of field: FortiasFrostRound1::nonce_e"]
        [::std::mem::offset_of!(FortiasFrostRound1, nonce_e) - 32usize];
    ["Offset of field: FortiasFrostRound1::commit_D"]
        [::std::mem::offset_of!(FortiasFrostRound1, commit_D) - 64usize];
    ["Offset of field: FortiasFrostRound1::commit_E"]
        [::std::mem::offset_of!(FortiasFrostRound1, commit_E) - 96usize];
};
extern "C" {
    pub fn fortias_frost_round1(out: *mut FortiasFrostRound1) -> FortiasResult;
}
extern "C" {
    pub fn fortias_frost_sign_share(
        my_state: *const FortiasFrostRound1,
        my_key_share: *const FortiasFrostShare,
        msg: *const u8,
        msg_len: usize,
        all_commits: *const u8,
        n_signers: usize,
        my_index: i32,
        sig_share_out: *mut FortiasFrostShare,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_frost_aggregate(
        shares: *const FortiasFrostShare,
        indices: *const i32,
        k: usize,
        all_commits: *const u8,
        msg: *const u8,
        msg_len: usize,
        sig_out: *mut FortiasSig64,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_frost_destroy_round1(state: *mut FortiasFrostRound1);
}
extern "C" {
    pub fn fortias_nullifier_derive(
        priv_: *const FortiasPrivKey32,
        context: *const u8,
        context_len: usize,
        out: *mut FortiasNullifier,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_rng_bytes(buf: *mut u8, len: usize) -> FortiasResult;
}
extern "C" {
    pub fn fortias_memzero(ptr: *mut ::std::os::raw::c_void, len: usize);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FortiasPrivKey {
    _unused: [u8; 0],
}
extern "C" {
    pub fn fortias_privkey_init();
}
extern "C" {
    pub fn fortias_privkey_cleanup();
}
extern "C" {
    pub fn fortias_privkey_ed25519_generate() -> *mut FortiasPrivKey;
}
extern "C" {
    pub fn fortias_privkey_ed25519_from_seed(seed: *const u8) -> *mut FortiasPrivKey;
}
extern "C" {
    pub fn fortias_privkey_ed25519_public(key: *const FortiasPrivKey, out: *mut u8) -> *mut u8;
}
extern "C" {
    pub fn fortias_privkey_ed25519_sign(
        key: *const FortiasPrivKey,
        msg: *const u8,
        msg_len: usize,
        sig: *mut u8,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn fortias_nullifier_derive_handle(
        key: *const FortiasPrivKey,
        context: *const u8,
        context_len: usize,
        out: *mut FortiasNullifier,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_privkey_derive_seal_key(
        key: *const FortiasPrivKey,
        info: *const u8,
        info_len: usize,
        seal_key: *mut u8,
    ) -> FortiasResult;
}
extern "C" {
    pub fn fortias_privkey_free(key: *mut FortiasPrivKey);
}
