//! Safe Rust wrappers over C11 FFI.
//!
//! Provides safe Rust interfaces over the C11 cryptographic core,
//! including identity management, signing, hashing, and random number generation.

// Auto-generated FFI bindings - not documented, generated by bindgen via build.rs.
/// Auto-generated FFI bindings to the C11 core library.
pub mod bindings;
pub mod hashing;
pub mod identity;
pub mod merkle;
pub mod rng;
pub mod signing;

pub use bindings::*;
